# Generated by Django 4.2.11 on 2025-03-20 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_news_testimonial_student_class_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
