# Generated by Django 4.2.11 on 2025-03-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_delete_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='is_event',
            field=models.BooleanField(default=False),
        ),
    ]
